/**
 * Expo config plugin: Android network security policy.
 *
 * By default Android allows or forbids cleartext traffic globally. We want
 * better: forbid HTTP everywhere, since the API token would travel in the clear
 * and be interceptable on a hostile network, except towards the loopback
 * addresses and the `10.0.2.2` alias through which the emulator reaches the
 * host machine.
 *
 * Those three addresses never leave the device or the development machine, so
 * the exception opens no real surface.
 */
const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const { promises: fs } = require('fs');
const path = require('path');

/** Hosts always allowed in cleartext: they never leave the machine. */
const ALWAYS_ALLOWED = ['localhost', '127.0.0.1', '10.0.2.2'];

function buildXml(hosts) {
  const entries = hosts
    .map((h) => `        <domain includeSubdomains="false">${h}</domain>`)
    .join('\n');

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withNetworkSecurity.js. Do not edit by hand. -->
<network-security-config>
    <!-- General rule: HTTPS required. -->
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>

    <!-- Exceptions limited to local development. -->
    <domain-config cleartextTrafficPermitted="true">
${entries}
    </domain-config>
</network-security-config>
`;
}

module.exports = function withNetworkSecurity(config) {
  // Extra development hosts, declared in app.json under
  // `extra.devCleartextHosts`, typically the development machine's IP so you
  // can test from a real phone on the local network, for example
  // ["192.168.1.x"]. In production the API goes over HTTPS, so the list stays
  // empty and cleartext HTTP is then refused everywhere except loopback and
  // the emulator.
  const extra = config.extra?.devCleartextHosts ?? [];
  const hosts = [...new Set([...ALWAYS_ALLOWED, ...extra])];

  if (extra.length > 0) {
    console.warn(
      `\n  Cleartext HTTP allowed to: ${extra.join(', ')}` +
        `\n  Remove from app.json (extra.devCleartextHosts) before any use outside a local network.\n`,
    );
  }

  // 1. Write the XML resource into the native project.
  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app/src/main/res/xml',
      );
      await fs.mkdir(dir, { recursive: true });
      await fs.writeFile(
        path.join(dir, 'network_security_config.xml'),
        buildXml(hosts),
        'utf8',
      );
      return cfg;
    },
  ]);

  // 2. Reference the resource and drop the global attribute the config replaces.
  return withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application?.[0];
    if (!application) return cfg;

    application.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    delete application.$['android:usesCleartextTraffic'];

    return cfg;
  });
};
